version: "3"

services:
   web:
      build: "./web"
      ports:
         - "8000:90"
   api:
      build: "./api"
      ports:
         - "5000:5000"
      links:
         - my_db
         
   my_db:
      build: "./db"
      ports:
         - "27017:27017"